export const FETCH_NYT_ARTICLES_REQUEST = 'FETCH_NYT_ARTICLES_REQUEST';
export const FETCH_NYT_ARTICLES_SUCCESS = 'FETCH_NYT_ARTICLES_SUCCESS';
export const FETCH_NYT_ARTICLES_FAILURE = 'FETCH_NYT_ARTICLES_FAILURE';
