export const FETCH_NEWS = 'FETCH_NEWS';
export const SET_NEWS = 'SET_NEWS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const SEARCH_ARTICLES_REQUEST = 'SEARCH_ARTICLES_REQUEST';
export const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS';
export const SEARCH_ARTICLES_FAILURE = 'SEARCH_ARTICLES_FAILURE';
